#!/usr/bin/env bash
set -e


script_path=$(dirname "$0")
pipfile_lock_path="$script_path/../Pipfile.lock"

if [ ! -f $pipfile_lock_path ]; then
    echo "'Pipfile.lock' not found. Generating via 'pipenv lock --dev'..."
    pipenv lock --dev
fi

pipenv sync --dev

./scripts/install-vendor-apps

export FLASK_ENV=development

pipenv run invenio collect -v
pipenv run invenio webpack clean buildall

