#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 RSL.
#
# rsl is free software; you can redistribute it and/or modify it under the
# terms of the MIT License; see LICENSE file for more details.

set -e

this_dir=$(pwd)

for d in vendor/* ; do
    [ -L "${d%/}" ] && continue
    cd $this_dir
    cd $d
    pip install -e .
done

cd $this_dir