#!/usr/bin/env bash
set -e

script_path=$(dirname "$0")

export FLASK_ENV=development


pipenv run invenio run \
       --cert "$script_path"/../docker/nginx/test.crt \
       --key "$script_path"/../docker/nginx/test.key & pid_server=$!

trap 'kill $pid_server &>/dev/null' EXIT

wait $pid_server
